// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(AplicationDBContext))]
    [Migration("20231122202432_AltaRegistrosVilla3")]
    partial class AltaRegistrosVilla3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FUM")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "ameno",
                            Detalle = "Ningun lugar",
                            FA = new DateTime(2023, 11, 22, 14, 24, 32, 656, DateTimeKind.Local).AddTicks(6089),
                            ImageUrl = "",
                            MetrosCuadrados = 1000,
                            Nombre = "En ningun Lugar",
                            Ocupantes = 100,
                            Tarifa = 1001.21m
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "ameno",
                            Detalle = "Ningun lugar",
                            FA = new DateTime(2023, 11, 22, 14, 24, 32, 656, DateTimeKind.Local).AddTicks(6100),
                            ImageUrl = "",
                            MetrosCuadrados = 1000,
                            Nombre = "En ningun Lugar",
                            Ocupantes = 100,
                            Tarifa = 1001.21m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
